name: davidbella
description: ""
meta_description: ""

markdown: redcarpet
pygments: true
logo: '/assets/images/profile.png'
paginate: 15

# Details for the RSS feed generator
url:            'http://davidbella.github.io/'
author:         'David Bella'

comments:
  provider: disqus
  disqus:
    short_name: davidbella
    api_key: yn4RP3aAY3Wc5yrJFrXfGPL5OPitsQbS50gKPYbGowbjTFa0YQYCwZk4GHkGuaBE